test

diff --git a/.github/workflows/check-version-updated.yml b/.github/workflows/check-version-updated.yml
--- a/.github/workflows/check-version-updated.yml
+++ b/.github/workflows/check-version-updated.yml
@@ -6,14 +6,19 @@ on:
     # branches: [develop]
 
 jobs:
-  CheckVersionUpdated:
+  version_diff:
     runs-on: ubuntu-latest
+    outputs:
+      chagned: ${{ steps.get_diff.outputs.changed }}
     steps:
       - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      - name: Check package version
-        uses: technote-space/package-version-check-action@v1
-        with:
-          BRANCH_PREFIX: develop
-          COMMIT_DISABLED: 1
+        run: git fetch origin ${{ github.base_ref }} --depth=1
+        id: get_diff
+        run: echo "changed=$(git diff origin/${{ github.base_ref }} HEAD --relative "./package.json" | grep "^+.\+version" | wc -l)" >> $GITHUB_OUTPUT
+  version_check:
+    runs-on: ubuntu-latest
+    needs: [version_diff]
+    if: needs.version_diff.outputs.chagned == '0'
+    run: |
+           echo "::error::package.json version update required."
+           exit 1
